#!/bin/bash

set -eu

yadm decrypt 

scripts=(
    $BOOTSTRAP_D/install-system-level-files.sh
    $BOOTSTRAP_D/install_emacs.sh
    $BOOTSTRAP_D/install_arch.sh
    $BOOTSTRAP_D/install_go.sh
)

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

function main() {
    for s in ${scripts[@]}; do
        printf "\n${BLUE}➜ Installing ${s}...${NORMAL}\n"
        sh ${s}
    done
}

main



