#!/bin/bash

set -eu

yadm decrypt 

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

# Use colors, but only if connected to a terminal, and that terminal
# supports them.
if command -v tput >/dev/null 2>&1; then
    ncolors=$(tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
    RED="$(tput setaf 1)"
    GREEN="$(tput setaf 2)"
    YELLOW="$(tput setaf 3)"
    BLUE="$(tput setaf 4)"
    BOLD="$(tput bold)"
    NORMAL="$(tput sgr0)"
else
    RED=""
    GREEN=""
    YELLOW=""
    BLUE=""
    BOLD=""
    NORMAL=""
fi

scripts=(
    "$BOOTSTRAP_D/install-system-level-files.sh"
    "$BOOTSTRAP_D/install_arch.sh"
    "$BOOTSTRAP_D/install_emacs.sh"
    "$BOOTSTRAP_D/install_go.sh"
    "$BOOTSTRAP_D/install_xmonad_repo.sh"
)

function main() {
    for s in ${scripts[@]}; do
        printf "\n${BLUE}➜ Installing ${s}...${NORMAL}\n"
        sh ${s}
    done
}

main



